### ISSUE TITLE
Updating/Moving directory

### ISSUE THREAD

**Issue by LonleyViper** [BOLL7708/OpenVRStartup#2]
Might be an obvious question. But when I initially set this up the directory was in my Downloads folder. If I move it, will that affect the script? How will updating the script affect how it runs.

Thanks!

**Comment by BOLL7708** [comment]
The application registers the manifest for itself on first launch, this will only happen once per app ID if I remember it correctly. To make sure you get it to automatically run in the new location you can remove the old manifest path from this file (or wherever your file is located): `C:\Program Files (x86)\Steam\config\appconfig.json`

As it's a JSON file make sure to not have an extra comma at the end of the items in the array, this will mean it does not pass validation and SteamVR will nuke it, resetting it to an empty file. You can paste the file contests into this website after editing if you want to make sure you're not screwing things up: https://jsonlint.com/

**Comment by LonleyViper** [comment]
Thanks BOLL!
