### ISSUE TITLE
Stop command not executing on SteamVR close

### ISSUE THREAD

**Issue by LonleyViper** [BOLL7708/OpenVRStartup#3]
Using the below cmd script in the stop folder.

`taskkill /im voicemeeterpro.exe /T /F`

Works fine when executed manually, doesnt work on SteamVR exit.

**Comment by LonleyViper** [comment]
Also noting the demo command doesnt execute either!

**Comment by BOLL7708** [comment]
Do you let the application window stay up after launching SteamVR? It's a program that runs in the terminal so it'll stick around in your taskbar until SteamVR shuts down. I've just tested the current release version in a new folder and it executes both start and stop scripts. 🤔

What do you see in the `OpenVRStartup.log` file that resides in the same folder as the executable? It should look like this if you just straight off ran it.
```
2021-02-04 00:53:21.761 Application starting (v0.10)
2021-02-04 00:53:22.849 OpenVR init success
2021-02-04 00:53:25.396 Found: 1 script(s) in ./start/
2021-02-04 00:53:25.396 Executing: ./start/demo_start.cmd from ./start/
2021-02-04 00:53:35.487 Found: 1 script(s) in ./stop/
2021-02-04 00:53:35.487 Executing: ./stop/demo_stop.cmd from ./stop/
2021-02-04 00:53:35.495 Application exiting, writing log
```

**Comment by LonleyViper** [comment]
The 'First Run Instructions' show up every time I start SteamVR. Cant seem to get it to go away unless I press enter 3 times.

There is no log in the folder?

**Comment by BOLL7708** [comment]
I realize there is a disconnect in expectations now, I should put in an additional message after pressing enter to continue as a confirmation that it happened even while waiting for shutdown.

As hinted at the application will now by default wait for shutdown as there is a demo script present, the thing is if you press enter more than once you will likely forcefully exit the application. That's what I expect from something running in the terminal in any case.

The log file is not written unless the program properly finishes executing, which means running until it shuts itself down, then it writes the log as to not dig a hole in your drive. If you press enter once, and then shutdown SteamVR (unless you removed demo_stop.cmd where it will shut down immediately by default) it should in theory write said log file.

And incidentally, the presence of that log files is what skips the introduction message. Clearly this change in functionality needs the introduction message to behave differently. Tell me if the above fixes your issue specifically, and I'll try to find time to rework this soon enough.

**Comment by LonleyViper** [comment]
That makes sense! It all works now thanks again dude!!
