### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Markcreator** [BOLL7708/OpenVRStartup#6]
Nice job with this project! I'd love to make a variation, but no LICENSE file is attached.
Would love to know what I can do with this!

**Comment by BOLL7708** [comment]
Would you be OK with a AGPL-3.0 license? I've done that so far for my applications, and MIT only for libraries. If I don't hear back before tomorrow I'll just add it after office hours😁

**Comment by Markcreator** [comment]
Sounds good to me!

**Comment by BOLL7708** [comment]
There we go, done :D
